backend:
  name: github
  repo: romanbobers-create/gvozdoder
  branch: main
  site_domain: https://gvozdoder-repo.netlify.app

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "music"
    label: "Музыка"
    folder: "content/music"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название трека", name: "title", widget: "string" }
      - { label: "Аудиофайл", name: "audio", widget: "file" }
      - { label: "Обложка", name: "cover", widget: "image", required: false }
      - { label: "Текст песни", name: "lyrics", widget: "markdown", required: false }
